<?php

use Illuminate\Database\Seeder;

class AssistsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('assists')->delete();
        
        \DB::table('assists')->insert(array (
            0 => 
            array (
                'id' => 1,
                'admin_id' => NULL,
                'player_id' => 0,
                'type' => 'register',
                'email_sent_player' => 'gabrielcaraballo2219072@gmail.com',
                'email_sent_admin' => 'admin@apuestasg.win',
                'status' => 1,
                'created_at' => '2020-09-30 14:16:16',
                'updated_at' => '2020-09-30 14:16:16',
            ),
            1 => 
            array (
                'id' => 2,
                'admin_id' => NULL,
                'player_id' => 0,
                'type' => 'register',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => 'admin@apuestasg.win',
                'status' => 1,
                'created_at' => '2020-09-30 14:16:24',
                'updated_at' => '2020-09-30 14:16:24',
            ),
            2 => 
            array (
                'id' => 3,
                'admin_id' => NULL,
                'player_id' => 0,
                'type' => 'register',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => 'admin@apuestasg.win',
                'status' => 1,
                'created_at' => '2020-09-30 14:32:54',
                'updated_at' => '2020-09-30 14:32:54',
            ),
            3 => 
            array (
                'id' => 4,
                'admin_id' => NULL,
                'player_id' => 0,
                'type' => 'register',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => 'admin@apuestasg.win',
                'status' => 1,
                'created_at' => '2020-09-30 14:37:00',
                'updated_at' => '2020-09-30 14:37:00',
            ),
            4 => 
            array (
                'id' => 5,
                'admin_id' => NULL,
                'player_id' => 0,
                'type' => 'register',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => 'admin@apuestasg.win',
                'status' => 1,
                'created_at' => '2020-09-30 14:39:44',
                'updated_at' => '2020-09-30 14:39:44',
            ),
            5 => 
            array (
                'id' => 6,
                'admin_id' => NULL,
                'player_id' => 0,
                'type' => 'register',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => 'admin@apuestasg.win',
                'status' => 1,
                'created_at' => '2020-09-30 14:45:03',
                'updated_at' => '2020-09-30 14:45:03',
            ),
            6 => 
            array (
                'id' => 7,
                'admin_id' => NULL,
                'player_id' => 0,
                'type' => 'register',
                'email_sent_player' => 'carmenbompart22@gmail.com',
                'email_sent_admin' => 'admin@apuestasg.win',
                'status' => 1,
                'created_at' => '2020-10-01 05:45:07',
                'updated_at' => '2020-10-01 05:45:07',
            ),
            7 => 
            array (
                'id' => 8,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-hipism',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-06 18:21:22',
                'updated_at' => '2020-10-06 18:21:22',
            ),
            8 => 
            array (
                'id' => 9,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-hipism',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-06 18:29:38',
                'updated_at' => '2020-10-06 18:29:38',
            ),
            9 => 
            array (
                'id' => 10,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-hipism',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-06 18:36:24',
                'updated_at' => '2020-10-06 18:36:24',
            ),
            10 => 
            array (
                'id' => 11,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-hipism',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-06 18:49:21',
                'updated_at' => '2020-10-06 18:49:21',
            ),
            11 => 
            array (
                'id' => 12,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-hipism',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-06 19:03:14',
                'updated_at' => '2020-10-06 19:03:14',
            ),
            12 => 
            array (
                'id' => 13,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-hipism',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-06 19:12:33',
                'updated_at' => '2020-10-06 19:12:33',
            ),
            13 => 
            array (
                'id' => 14,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-hipism',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-07 07:10:01',
                'updated_at' => '2020-10-07 07:10:01',
            ),
            14 => 
            array (
                'id' => 15,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-07 19:06:57',
                'updated_at' => '2020-10-07 19:06:57',
            ),
            15 => 
            array (
                'id' => 16,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-07 19:13:26',
                'updated_at' => '2020-10-07 19:13:26',
            ),
            16 => 
            array (
                'id' => 17,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-07 19:14:45',
                'updated_at' => '2020-10-07 19:14:45',
            ),
            17 => 
            array (
                'id' => 18,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-07 19:15:42',
                'updated_at' => '2020-10-07 19:15:42',
            ),
            18 => 
            array (
                'id' => 19,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-07 19:16:44',
                'updated_at' => '2020-10-07 19:16:44',
            ),
            19 => 
            array (
                'id' => 20,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-07 19:17:52',
                'updated_at' => '2020-10-07 19:17:52',
            ),
            20 => 
            array (
                'id' => 21,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-07 19:18:54',
                'updated_at' => '2020-10-07 19:18:54',
            ),
            21 => 
            array (
                'id' => 22,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-07 19:23:05',
                'updated_at' => '2020-10-07 19:23:05',
            ),
            22 => 
            array (
                'id' => 23,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-hipism',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-07 19:34:08',
                'updated_at' => '2020-10-07 19:34:08',
            ),
            23 => 
            array (
                'id' => 24,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-07 19:34:42',
                'updated_at' => '2020-10-07 19:34:42',
            ),
            24 => 
            array (
                'id' => 25,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-08 17:55:32',
                'updated_at' => '2020-10-08 17:55:32',
            ),
            25 => 
            array (
                'id' => 26,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-10 13:30:13',
                'updated_at' => '2020-10-10 13:30:13',
            ),
            26 => 
            array (
                'id' => 27,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-10 13:31:17',
                'updated_at' => '2020-10-10 13:31:17',
            ),
            27 => 
            array (
                'id' => 28,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-10 13:32:09',
                'updated_at' => '2020-10-10 13:32:09',
            ),
            28 => 
            array (
                'id' => 29,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-10 13:33:06',
                'updated_at' => '2020-10-10 13:33:06',
            ),
            29 => 
            array (
                'id' => 30,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-10 13:33:28',
                'updated_at' => '2020-10-10 13:33:28',
            ),
            30 => 
            array (
                'id' => 31,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-10 13:33:59',
                'updated_at' => '2020-10-10 13:33:59',
            ),
            31 => 
            array (
                'id' => 32,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-10 13:35:43',
                'updated_at' => '2020-10-10 13:35:43',
            ),
            32 => 
            array (
                'id' => 33,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-10 13:37:11',
                'updated_at' => '2020-10-10 13:37:11',
            ),
            33 => 
            array (
                'id' => 34,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-10 13:37:39',
                'updated_at' => '2020-10-10 13:37:39',
            ),
            34 => 
            array (
                'id' => 35,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-10 13:37:57',
                'updated_at' => '2020-10-10 13:37:57',
            ),
            35 => 
            array (
                'id' => 36,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-10 13:38:25',
                'updated_at' => '2020-10-10 13:38:25',
            ),
            36 => 
            array (
                'id' => 37,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-10 23:40:51',
                'updated_at' => '2020-10-10 23:40:51',
            ),
            37 => 
            array (
                'id' => 38,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 00:17:14',
                'updated_at' => '2020-10-11 00:17:14',
            ),
            38 => 
            array (
                'id' => 39,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 00:23:36',
                'updated_at' => '2020-10-11 00:23:36',
            ),
            39 => 
            array (
                'id' => 40,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 00:29:43',
                'updated_at' => '2020-10-11 00:29:43',
            ),
            40 => 
            array (
                'id' => 41,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 08:53:47',
                'updated_at' => '2020-10-11 08:53:47',
            ),
            41 => 
            array (
                'id' => 42,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 08:53:53',
                'updated_at' => '2020-10-11 08:53:53',
            ),
            42 => 
            array (
                'id' => 43,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 08:54:09',
                'updated_at' => '2020-10-11 08:54:09',
            ),
            43 => 
            array (
                'id' => 44,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 08:54:16',
                'updated_at' => '2020-10-11 08:54:16',
            ),
            44 => 
            array (
                'id' => 45,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 08:54:24',
                'updated_at' => '2020-10-11 08:54:24',
            ),
            45 => 
            array (
                'id' => 46,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 09:10:06',
                'updated_at' => '2020-10-11 09:10:06',
            ),
            46 => 
            array (
                'id' => 47,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 09:10:16',
                'updated_at' => '2020-10-11 09:10:16',
            ),
            47 => 
            array (
                'id' => 48,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 09:16:10',
                'updated_at' => '2020-10-11 09:16:10',
            ),
            48 => 
            array (
                'id' => 49,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 12:36:33',
                'updated_at' => '2020-10-11 12:36:33',
            ),
            49 => 
            array (
                'id' => 50,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 12:46:26',
                'updated_at' => '2020-10-11 12:46:26',
            ),
            50 => 
            array (
                'id' => 51,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 12:47:11',
                'updated_at' => '2020-10-11 12:47:11',
            ),
            51 => 
            array (
                'id' => 52,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 12:48:58',
                'updated_at' => '2020-10-11 12:48:58',
            ),
            52 => 
            array (
                'id' => 53,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 13:24:17',
                'updated_at' => '2020-10-11 13:24:17',
            ),
            53 => 
            array (
                'id' => 54,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 13:27:30',
                'updated_at' => '2020-10-11 13:27:30',
            ),
            54 => 
            array (
                'id' => 55,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 13:32:03',
                'updated_at' => '2020-10-11 13:32:03',
            ),
            55 => 
            array (
                'id' => 56,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 13:33:04',
                'updated_at' => '2020-10-11 13:33:04',
            ),
            56 => 
            array (
                'id' => 57,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 13:39:58',
                'updated_at' => '2020-10-11 13:39:58',
            ),
            57 => 
            array (
                'id' => 58,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 13:47:03',
                'updated_at' => '2020-10-11 13:47:03',
            ),
            58 => 
            array (
                'id' => 59,
                'admin_id' => NULL,
                'player_id' => 2,
                'type' => 'ticket-sport',
                'email_sent_player' => 'master@apuestasg.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 14:49:35',
                'updated_at' => '2020-10-11 14:49:35',
            ),
            59 => 
            array (
                'id' => 60,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 14:54:15',
                'updated_at' => '2020-10-11 14:54:15',
            ),
            60 => 
            array (
                'id' => 61,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 15:00:35',
                'updated_at' => '2020-10-11 15:00:35',
            ),
            61 => 
            array (
                'id' => 62,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 16:07:28',
                'updated_at' => '2020-10-11 16:07:28',
            ),
            62 => 
            array (
                'id' => 63,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-11 16:36:13',
                'updated_at' => '2020-10-11 16:36:13',
            ),
            63 => 
            array (
                'id' => 64,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-12 19:34:06',
                'updated_at' => '2020-10-12 19:34:06',
            ),
            64 => 
            array (
                'id' => 65,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-12 19:34:40',
                'updated_at' => '2020-10-12 19:34:40',
            ),
            65 => 
            array (
                'id' => 66,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-12 19:35:20',
                'updated_at' => '2020-10-12 19:35:20',
            ),
            66 => 
            array (
                'id' => 67,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-12 19:35:57',
                'updated_at' => '2020-10-12 19:35:57',
            ),
            67 => 
            array (
                'id' => 68,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-12 19:36:13',
                'updated_at' => '2020-10-12 19:36:13',
            ),
            68 => 
            array (
                'id' => 69,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-12 19:36:31',
                'updated_at' => '2020-10-12 19:36:31',
            ),
            69 => 
            array (
                'id' => 70,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-12 19:36:52',
                'updated_at' => '2020-10-12 19:36:52',
            ),
            70 => 
            array (
                'id' => 71,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-13 06:49:55',
                'updated_at' => '2020-10-13 06:49:55',
            ),
            71 => 
            array (
                'id' => 72,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-13 06:50:16',
                'updated_at' => '2020-10-13 06:50:16',
            ),
            72 => 
            array (
                'id' => 73,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-20 21:32:36',
                'updated_at' => '2020-10-20 21:32:36',
            ),
            73 => 
            array (
                'id' => 74,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-20 21:33:00',
                'updated_at' => '2020-10-20 21:33:00',
            ),
            74 => 
            array (
                'id' => 75,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-20 21:33:48',
                'updated_at' => '2020-10-20 21:33:48',
            ),
            75 => 
            array (
                'id' => 76,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-20 21:34:19',
                'updated_at' => '2020-10-20 21:34:19',
            ),
            76 => 
            array (
                'id' => 77,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-20 21:35:22',
                'updated_at' => '2020-10-20 21:35:22',
            ),
            77 => 
            array (
                'id' => 78,
                'admin_id' => NULL,
                'player_id' => 29,
                'type' => 'ticket-sport',
                'email_sent_player' => 'gabrielcaraballo1907@gmail.com',
                'email_sent_admin' => NULL,
                'status' => 1,
                'created_at' => '2020-10-20 21:35:48',
                'updated_at' => '2020-10-20 21:35:48',
            ),
        ));
        
        
    }
}