<?php

use Illuminate\Database\Seeder;

class BetTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('bet_types')->delete();
        
        \DB::table('bet_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'standard',
                'description' => 'Resultado del partido',
                'adding' => NULL,
                'index' => NULL,
                'option' => 'full',
                'importance' => 50,
                'category_id' => 1,
                'created_at' => '2020-06-10 22:31:33',
                'updated_at' => '2020-10-02 14:35:33',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'double-chance',
                'description' => 'Doble oportunidad',
                'adding' => NULL,
                'index' => NULL,
                'option' => '2option',
                'importance' => 50,
                'category_id' => 1,
                'created_at' => '2020-06-10 22:31:33',
                'updated_at' => '2020-10-02 14:35:33',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'handicap',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => 'dif',
                'importance' => 50,
                'category_id' => 1,
                'created_at' => '2020-06-10 22:31:33',
                'updated_at' => '2020-10-02 14:35:33',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'points-more-less-than',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 1,
                'created_at' => '2020-06-10 22:31:33',
                'updated_at' => '2020-10-02 14:35:33',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'section-win',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 1,
                'created_at' => '2020-06-10 22:31:33',
                'updated_at' => '2020-10-02 14:35:33',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'section-points-more-less',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 1,
                'created_at' => '2020-06-10 22:31:33',
                'updated_at' => '2020-10-02 14:35:33',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'score-both',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 1,
                'created_at' => '2020-06-10 22:31:33',
                'updated_at' => '2020-10-02 14:35:33',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'standard',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 2,
                'created_at' => '2020-06-12 00:14:17',
                'updated_at' => '2020-10-02 16:00:13',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'points-more-less-than',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 2,
                'created_at' => '2020-06-12 00:14:18',
                'updated_at' => '2020-10-02 16:00:13',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'standard',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 3,
                'created_at' => '2020-06-13 00:16:59',
                'updated_at' => '2020-10-02 14:37:29',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'handicap',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 3,
                'created_at' => '2020-06-13 00:16:59',
                'updated_at' => '2020-10-02 14:37:29',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'points-more-less-than',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 3,
                'created_at' => '2020-06-13 00:17:00',
                'updated_at' => '2020-10-02 14:37:29',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'handicap-halftime',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 3,
                'created_at' => '2020-06-13 00:17:00',
                'updated_at' => '2020-10-02 14:37:29',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'points-more-less-halftime',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 3,
                'created_at' => '2020-06-13 00:17:00',
                'updated_at' => '2020-10-02 16:00:23',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'standard',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 4,
                'created_at' => '2020-06-13 03:24:31',
                'updated_at' => '2020-10-02 16:00:02',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'standard',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 10,
                'created_at' => '2020-06-20 22:36:33',
                'updated_at' => '2020-10-02 16:00:48',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'points-more-less-than',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 4,
                'created_at' => '2020-06-22 01:00:16',
                'updated_at' => '2020-10-02 16:00:02',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'games-more-less-than',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 4,
                'created_at' => '2020-06-24 05:00:15',
                'updated_at' => '2020-10-02 16:00:02',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'standard',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 100,
                'category_id' => 6,
                'created_at' => '2020-08-09 15:48:17',
                'updated_at' => '2020-08-09 15:48:17',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'points-more-less-than',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 100,
                'category_id' => 6,
                'created_at' => '2020-08-09 15:48:17',
                'updated_at' => '2020-08-09 15:48:17',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'standard-full',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 100,
                'category_id' => 6,
                'created_at' => '2020-08-09 15:48:17',
                'updated_at' => '2020-08-09 15:48:17',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'double-chance',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 100,
                'category_id' => 6,
                'created_at' => '2020-08-09 15:48:17',
                'updated_at' => '2020-08-09 15:48:17',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'handicap',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 100,
                'category_id' => 6,
                'created_at' => '2020-08-09 15:48:17',
                'updated_at' => '2020-08-09 15:48:17',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'score-both-minimum',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 100,
                'category_id' => 6,
                'created_at' => '2020-08-09 15:48:17',
                'updated_at' => '2020-08-09 15:48:17',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'head-to-head',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 1,
                'created_at' => '2020-08-30 23:00:09',
                'updated_at' => '2020-10-02 14:35:33',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'section-win',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 2,
                'created_at' => '2020-08-30 23:00:28',
                'updated_at' => '2020-10-02 21:00:13',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'halftime-win',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 3,
                'created_at' => '2020-08-31 00:00:26',
                'updated_at' => '2020-10-02 14:37:29',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'section-win',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 4,
                'created_at' => '2020-08-31 00:00:29',
                'updated_at' => '2020-10-02 16:00:02',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'section-win',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 3,
                'created_at' => '2020-08-31 14:00:19',
                'updated_at' => '2020-10-02 14:37:29',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'section-handicap',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 3,
                'created_at' => '2020-08-31 14:00:19',
                'updated_at' => '2020-10-02 14:37:29',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'section-games-more-less',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 4,
                'created_at' => '2020-09-04 11:05:47',
                'updated_at' => '2020-10-02 16:00:02',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'tie-break-in-set',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 4,
                'created_at' => '2020-09-08 01:06:14',
                'updated_at' => '2020-10-03 01:00:04',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'standard',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 5,
                'created_at' => '2020-09-14 18:23:36',
                'updated_at' => '2020-10-02 16:00:45',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'handicap',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 5,
                'created_at' => '2020-09-14 18:23:36',
                'updated_at' => '2020-10-02 16:00:45',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'points-more-less-than',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 5,
                'created_at' => '2020-09-14 18:23:36',
                'updated_at' => '2020-10-02 16:00:45',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'halftime-win',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 5,
                'created_at' => '2020-09-14 18:23:36',
                'updated_at' => '2020-10-02 16:00:45',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'next-point',
                'description' => '',
                'adding' => NULL,
                'index' => NULL,
                'option' => NULL,
                'importance' => 50,
                'category_id' => 5,
                'created_at' => '2020-10-13 15:00:19',
                'updated_at' => '2020-10-13 15:00:19',
            ),
        ));
        
        
    }
}