<?php

use Illuminate\Database\Seeder;

class LeaguesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('leagues')->delete();
        
        \DB::table('leagues')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'MLB',
                'name_uk' => '["25301","10562301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/baseball/major-league-baseball/',
                'importance' => '10000.00',
                'country_id' => 226,
                'category_id' => 2,
                'match_structure_id' => 3,
                'created_at' => '2019-11-11 12:32:10',
                'updated_at' => '2020-10-23 12:25:17',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Primera división de Paraguay',
                'name_uk' => '["3133301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/paraguay/división-profesional/',
                'importance' => NULL,
                'country_id' => 182,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-11-11 12:25:58',
                'updated_at' => '2020-07-21 18:48:20',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'NBA',
                'name_uk' => '["177301","10561301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/basketball/nba/',
                'importance' => '100.00',
                'country_id' => 226,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2019-11-11 12:27:36',
                'updated_at' => '2020-09-14 18:17:07',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'NFL',
                'name_uk' => '["47301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/american-football/nfl/',
                'importance' => '100.00',
                'country_id' => 226,
                'category_id' => 5,
                'match_structure_id' => 0,
                'created_at' => '2019-11-11 12:28:40',
                'updated_at' => '2020-09-14 18:23:34',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'NCAA',
                'name_uk' => '["85301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/american-football/division-i-bowl/',
                'importance' => '90.00',
                'country_id' => 226,
                'category_id' => 5,
                'match_structure_id' => 0,
                'created_at' => '2019-11-11 12:31:02',
                'updated_at' => '2020-10-23 07:44:09',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'NHL',
                'name_uk' => '["94235301","634210-10562301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/ice-hockey/nhl/',
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 6,
                'match_structure_id' => 0,
                'created_at' => '2019-11-11 12:32:27',
                'updated_at' => '2020-10-22 14:00:09',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'AHL',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/ice-hockey/american-hockey-league/',
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 6,
                'match_structure_id' => 0,
                'created_at' => '2019-11-11 12:33:42',
                'updated_at' => '2019-11-11 12:33:42',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Boxeo internacional',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/boxing/professional-boxing/',
                'importance' => NULL,
                'country_id' => 241,
                'category_id' => 9,
                'match_structure_id' => 0,
                'created_at' => '2019-11-11 08:40:23',
                'updated_at' => '2019-11-11 08:40:23',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'LNB',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/basketball/argentina/lnb/',
                'importance' => NULL,
                'country_id' => 11,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2019-11-11 08:41:59',
                'updated_at' => '2019-11-11 08:41:59',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'ATP World Tour Finals',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/nitto-atp-finals/',
                'importance' => NULL,
                'country_id' => 241,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2019-11-11 08:51:03',
                'updated_at' => '2019-11-11 08:51:03',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'LaLiga',
                'name_uk' => '[36301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/spain/primera-divisi%C3%B3n/',
                'importance' => '1000.00',
                'country_id' => 66,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-11-11 11:17:11',
                'updated_at' => '2020-10-22 14:03:10',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Série A de Brasil',
                'name_uk' => '["83301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/brazil/campeonato-brasileiro-s%C3%A9rie-a/',
                'importance' => NULL,
                'country_id' => 31,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-11-11 11:22:20',
                'updated_at' => '2020-10-10 13:19:03',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'NCAAB',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/basketball/ncaa/',
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2019-11-12 06:08:10',
                'updated_at' => '2019-11-12 06:08:10',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Copa de África de Naciones',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/africa/african-cup-of-nations-qualification/',
                'importance' => NULL,
                'country_id' => 246,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-11-19 05:29:14',
                'updated_at' => '2019-11-19 05:29:14',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'UEFA Euro 2020',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/european-championship-qualification/',
                'importance' => '100.00',
                'country_id' => 245,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-11-19 05:31:37',
                'updated_at' => '2019-12-20 19:12:42',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'FA Cup de Inglaterra',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/england/fa-cup/',
                'importance' => '50.00',
                'country_id' => 104,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-11-19 05:34:00',
                'updated_at' => '2019-12-20 19:12:38',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Ligue 1 de Francia',
                'name_uk' => '["4301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/france/le-championnat/',
                'importance' => '70.00',
                'country_id' => 73,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-03 08:14:49',
                'updated_at' => '2020-10-25 02:37:02',
            ),
            17 => 
            array (
                'id' => 19,
                'name' => 'Premier League de Inglaterra',
                'name_uk' => '[1301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/england/premier-league/',
                'importance' => '97.00',
                'country_id' => 104,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-03 08:17:19',
                'updated_at' => '2020-06-16 18:54:46',
            ),
            18 => 
            array (
                'id' => 20,
                'name' => 'NBB',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/basketball/brazil/novo-basquete-brasil/',
                'importance' => NULL,
                'country_id' => 31,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2019-12-03 08:19:51',
                'updated_at' => '2019-12-03 08:19:51',
            ),
            19 => 
            array (
                'id' => 21,
                'name' => 'Primera división de Argentina',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/argentina/argentina-superliga-de-futbol/',
                'importance' => NULL,
                'country_id' => 11,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-08 12:32:36',
                'updated_at' => '2019-12-08 12:32:36',
            ),
            20 => 
            array (
                'id' => 22,
                'name' => 'Primera división de Bolivia',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/bolivia/liga-de-f%C3%BAtbol-profesional-boliviano/',
                'importance' => NULL,
                'country_id' => 30,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-08 12:39:37',
                'updated_at' => '2019-12-08 12:39:37',
            ),
            21 => 
            array (
                'id' => 23,
                'name' => 'Liga de Campeones de Europa',
                'name_uk' => '["742110","virtual_championsLeagueMatches"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/uefa-champions-league/',
                'importance' => '1000.00',
                'country_id' => 245,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-10 10:52:44',
                'updated_at' => '2020-10-27 07:17:15',
            ),
            22 => 
            array (
                'id' => 24,
                'name' => 'Bundesliga de Alemania',
                'name_uk' => '[42301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/germany/fu%C3%9Fball-bundesliga/',
                'importance' => '99.00',
                'country_id' => 55,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-13 05:46:41',
                'updated_at' => '2019-12-20 19:12:21',
            ),
            23 => 
            array (
                'id' => 25,
                'name' => 'Eredivisie de Holanda',
                'name_uk' => '["39301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/netherlands/eredivisie/',
                'importance' => '50.00',
                'country_id' => 162,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-13 05:51:21',
                'updated_at' => '2020-10-20 18:41:44',
            ),
            24 => 
            array (
                'id' => 26,
                'name' => 'Superliga Danesa - Grupo de campeonato',
                'name_uk' => '[58478301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/denmark/alka-superligaen/',
                'importance' => '10.00',
                'country_id' => 57,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-16 06:07:08',
                'updated_at' => '2020-06-20 22:17:39',
            ),
            25 => 
            array (
                'id' => 27,
                'name' => 'Serie A de Italia',
                'name_uk' => '[33301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/italy/serie-a/',
                'importance' => '90.00',
                'country_id' => 108,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-16 06:40:26',
                'updated_at' => '2020-06-19 20:45:14',
            ),
            26 => 
            array (
                'id' => 29,
                'name' => 'Primera división de Portugal',
                'name_uk' => '[52301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/portugal/portuguese-liga-sagres/',
                'importance' => NULL,
                'country_id' => 180,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-16 06:43:12',
                'updated_at' => '2019-12-16 06:43:12',
            ),
            27 => 
            array (
                'id' => 30,
                'name' => 'Superliga de Turquía',
                'name_uk' => '[62301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/turkey/super-lig/',
                'importance' => NULL,
                'country_id' => 220,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-16 06:44:58',
                'updated_at' => '2020-06-11 21:39:26',
            ),
            28 => 
            array (
                'id' => 31,
                'name' => 'Copa de Bélgica',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/belgium/croky-cup/',
                'importance' => '50.00',
                'country_id' => 21,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-16 06:50:11',
                'updated_at' => '2019-12-19 07:38:35',
            ),
            29 => 
            array (
                'id' => 32,
                'name' => 'Copa del Rey de España',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/spain/copa-del-rey/',
                'importance' => '100.00',
                'country_id' => 66,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-16 06:51:09',
                'updated_at' => '2019-12-20 19:11:18',
            ),
            30 => 
            array (
                'id' => 33,
                'name' => 'Copa de la Liga',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/france/coupe-de-la-ligue/',
                'importance' => NULL,
                'country_id' => 73,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-16 06:59:59',
                'updated_at' => '2019-12-16 06:59:59',
            ),
            31 => 
            array (
                'id' => 34,
                'name' => 'Copa de los Países Bajos',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/netherlands/knvb-beker/',
                'importance' => '40.00',
                'country_id' => 162,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-16 07:01:26',
                'updated_at' => '2019-12-19 07:38:49',
            ),
            32 => 
            array (
                'id' => 35,
                'name' => 'Copa de la Liga de Inglaterra',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/england/efl-cup/',
                'importance' => NULL,
                'country_id' => 104,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-16 07:03:05',
                'updated_at' => '2019-12-16 07:03:05',
            ),
            33 => 
            array (
                'id' => 36,
                'name' => 'Copa de Turquía',
                'name_uk' => '[63301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/turkey/t%C3%BCrkiye-kupasi/',
                'importance' => NULL,
                'country_id' => 220,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-16 07:04:51',
                'updated_at' => '2020-06-16 05:51:00',
            ),
            34 => 
            array (
                'id' => 37,
                'name' => 'WTA 125K Limoges',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/france/open-bls-de-limoges/',
                'importance' => NULL,
                'country_id' => 73,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2019-12-16 07:14:01',
                'updated_at' => '2019-12-16 07:14:01',
            ),
            35 => 
            array (
                'id' => 38,
                'name' => 'LVBP',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '100.00',
                'country_id' => 231,
                'category_id' => 2,
                'match_structure_id' => 3,
                'created_at' => '2019-12-16 07:49:57',
                'updated_at' => '2019-12-20 19:11:25',
            ),
            36 => 
            array (
                'id' => 39,
                'name' => 'Mundial de Clubes de la FIFA',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/world-club-cup/',
                'importance' => '100.00',
                'country_id' => 241,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-16 14:09:29',
                'updated_at' => '2019-12-16 14:13:46',
            ),
            37 => 
            array (
                'id' => 40,
                'name' => 'A-League de Australia',
                'name_uk' => '["144301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/australia/hyundai-a-league/',
                'importance' => NULL,
                'country_id' => 14,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-19 13:24:17',
                'updated_at' => '2020-07-18 12:06:17',
            ),
            38 => 
            array (
                'id' => 41,
                'name' => 'Campeonato mundial de tenis masculino de Abu Dabi',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '20.00',
                'country_id' => 2,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2019-12-20 09:04:58',
                'updated_at' => '2019-12-20 19:11:33',
            ),
            39 => 
            array (
                'id' => 42,
                'name' => 'Primera división de Egipto',
                'name_uk' => '["38612301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/egypt/premier-league/',
                'importance' => NULL,
                'country_id' => 63,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-24 04:57:13',
                'updated_at' => '2020-10-08 15:55:09',
            ),
            40 => 
            array (
                'id' => 43,
                'name' => 'Serie Nacional de Cuba',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 50,
                'category_id' => 2,
                'match_structure_id' => 3,
                'created_at' => '2019-12-24 05:45:56',
                'updated_at' => '2019-12-24 05:45:56',
            ),
            41 => 
            array (
                'id' => 44,
                'name' => 'KHL',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/ice-hockey/kontinental-hockey-league/',
                'importance' => NULL,
                'country_id' => 187,
                'category_id' => 6,
                'match_structure_id' => 0,
                'created_at' => '2019-12-24 18:22:02',
                'updated_at' => '2019-12-24 18:22:02',
            ),
            42 => 
            array (
                'id' => 45,
                'name' => 'Liga MX',
                'name_uk' => '["28301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/mexico/liga-mx/',
                'importance' => NULL,
                'country_id' => 153,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-26 08:25:07',
                'updated_at' => '2020-07-23 18:17:58',
            ),
            43 => 
            array (
                'id' => 46,
                'name' => 'Premiership de Escocia',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/scotland/scottish-premiership/',
                'importance' => NULL,
                'country_id' => 248,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2019-12-28 18:17:45',
                'updated_at' => '2019-12-28 18:17:45',
            ),
            44 => 
            array (
                'id' => 47,
                'name' => 'ABL',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/baseball/australia/australian-baseball-league/',
                'importance' => NULL,
                'country_id' => 14,
                'category_id' => 2,
                'match_structure_id' => 3,
                'created_at' => '2019-12-28 18:24:50',
                'updated_at' => '2019-12-28 18:24:50',
            ),
            45 => 
            array (
                'id' => 48,
                'name' => 'ATP Cup',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/atp-cup/',
                'importance' => NULL,
                'country_id' => 14,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-01-02 06:30:19',
                'updated_at' => '2020-01-02 06:30:19',
            ),
            46 => 
            array (
                'id' => 49,
                'name' => 'Euroliga',
                'name_uk' => '["2026010"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/basketball/euroleague-men/',
                'importance' => '99.00',
                'country_id' => 245,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2020-01-02 06:37:07',
                'updated_at' => '2020-10-08 18:13:01',
            ),
            47 => 
            array (
                'id' => 50,
                'name' => 'Copa de Francia',
                'name_uk' => '["77301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/france/coupe-de-france/',
                'importance' => NULL,
                'country_id' => 73,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-01-04 06:16:38',
                'updated_at' => '2020-07-23 18:17:09',
            ),
            48 => 
            array (
                'id' => 51,
                'name' => 'Superliga de Grecia',
                'name_uk' => '["127301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/greece/super-league-greece/',
                'importance' => '20.00',
                'country_id' => 87,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-01-04 06:18:06',
                'updated_at' => '2020-10-20 18:40:01',
            ),
            49 => 
            array (
                'id' => 52,
                'name' => 'WTA Abierto de Auckland',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/asb-classic/',
                'importance' => NULL,
                'country_id' => 167,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-01-04 06:22:13',
                'updated_at' => '2020-01-04 06:22:13',
            ),
            50 => 
            array (
                'id' => 53,
                'name' => 'WTA Abierto de Auckland - Clasificatoria',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/wta-asb-classic-qualification/',
                'importance' => NULL,
                'country_id' => 167,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-01-04 06:24:34',
                'updated_at' => '2020-01-04 06:24:34',
            ),
            51 => 
            array (
                'id' => 54,
                'name' => 'ATP Torneo de Doha - Clasificatoria',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/atp-qatar-exxonmobil-open-qualification/',
                'importance' => NULL,
                'country_id' => 183,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-01-04 06:25:55',
                'updated_at' => '2020-01-04 06:25:55',
            ),
            52 => 
            array (
                'id' => 55,
                'name' => 'WTA Torneo de Brisbane - Clasificatoria',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/brisbane-international-women\'s-singles-qualification/',
                'importance' => NULL,
                'country_id' => 14,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-01-04 06:29:20',
                'updated_at' => '2020-01-04 06:29:20',
            ),
            53 => 
            array (
                'id' => 56,
                'name' => 'WTA Abierto de Shenzhen - Clasificatoria',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/wta-shenzhen-gemdale-open-qualification/',
                'importance' => NULL,
                'country_id' => 47,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-01-04 06:30:40',
                'updated_at' => '2020-01-04 06:30:40',
            ),
            54 => 
            array (
                'id' => 57,
                'name' => 'WTA Abierto de Shenzhen',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/wta-shenzhen-gemdale-open/',
                'importance' => NULL,
                'country_id' => 47,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-01-04 06:31:35',
                'updated_at' => '2020-01-04 06:31:35',
            ),
            55 => 
            array (
                'id' => 58,
                'name' => 'WTA Torneo de Brisbane',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/brisbane-international-women\'s-singles/',
                'importance' => NULL,
                'country_id' => 14,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-01-05 14:33:39',
                'updated_at' => '2020-01-05 14:33:39',
            ),
            56 => 
            array (
                'id' => 59,
                'name' => 'Abierto de Australia Masculino',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/australian-open-men\'s-singles/',
                'importance' => '100.00',
                'country_id' => 14,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-01-25 12:07:32',
                'updated_at' => '2020-01-25 12:09:05',
            ),
            57 => 
            array (
                'id' => 60,
                'name' => 'Abierto de Australia Femenino',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/australian-open-women\'s-singles/',
                'importance' => '90.00',
                'country_id' => 14,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-01-25 12:08:10',
                'updated_at' => '2020-01-25 12:09:03',
            ),
            58 => 
            array (
                'id' => 61,
                'name' => 'Liga Pro de Bélgica',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/belgium/belgium-first-division-a/',
                'importance' => NULL,
                'country_id' => 21,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-15 18:51:15',
                'updated_at' => '2020-02-15 18:51:15',
            ),
            59 => 
            array (
                'id' => 62,
                'name' => 'Primera División de Chile',
                'name_uk' => '["67280301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/chile/primera-divisi%C3%B3n/',
                'importance' => NULL,
                'country_id' => 45,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-15 18:53:20',
                'updated_at' => '2020-10-08 15:54:23',
            ),
            60 => 
            array (
                'id' => 63,
                'name' => 'Liga Águila de Colombia',
                'name_uk' => '["19232301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/colombia/liga-%C3%A1guila/',
                'importance' => NULL,
                'country_id' => 48,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-15 18:55:00',
                'updated_at' => '2020-10-08 16:06:33',
            ),
            61 => 
            array (
                'id' => 64,
                'name' => 'Primera División de Costa Rica',
                'name_uk' => '[94357301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/costa-rica/primera-divisi%C3%B3n-de-costa-rica/',
                'importance' => NULL,
                'country_id' => 49,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-15 18:58:43',
                'updated_at' => '2020-06-22 18:29:12',
            ),
            62 => 
            array (
                'id' => 65,
                'name' => 'HNL de Croacia',
                'name_uk' => '[48301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/croatia/prva-hnl/',
                'importance' => NULL,
                'country_id' => 96,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-15 18:59:45',
                'updated_at' => '2020-06-11 21:44:58',
            ),
            63 => 
            array (
                'id' => 66,
                'name' => 'Serie A de Ecuador',
                'name_uk' => '["16887301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/ecuador/campeonato-ecuatoriano-de-f%C3%BAtbol-de-la-serie-a/',
                'importance' => NULL,
                'country_id' => 61,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-15 19:01:01',
                'updated_at' => '2020-08-17 16:29:16',
            ),
            64 => 
            array (
                'id' => 67,
                'name' => 'LaLiga Segunda División de España',
                'name_uk' => '[37301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/spain/segunda-division/',
                'importance' => '0.00',
                'country_id' => 66,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-15 19:02:32',
                'updated_at' => '2020-06-14 16:33:07',
            ),
            65 => 
            array (
                'id' => 68,
                'name' => 'I-League de India',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/india/i-league/',
                'importance' => NULL,
                'country_id' => 103,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-15 19:06:23',
                'updated_at' => '2020-02-15 19:06:23',
            ),
            66 => 
            array (
                'id' => 69,
                'name' => 'Liga Panameña de Fútbol',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/panama/liga-paname%C3%B1a-de-f%C3%BAtbol/',
                'importance' => NULL,
                'country_id' => 169,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-15 19:09:26',
                'updated_at' => '2020-02-15 19:09:26',
            ),
            67 => 
            array (
                'id' => 70,
                'name' => 'Primera División de Perú',
                'name_uk' => '["34467301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/peru/torneo-descentralizado-de-futbol-profesional-peruano/',
                'importance' => '100.00',
                'country_id' => 170,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-15 19:10:32',
                'updated_at' => '2020-09-17 10:12:49',
            ),
            68 => 
            array (
                'id' => 71,
                'name' => 'Primera División de Uruguay',
                'name_uk' => '["57776301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/uruguay/liga-profesional-de-primera-divisi%C3%B3n/',
                'importance' => NULL,
                'country_id' => 227,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-15 19:11:40',
                'updated_at' => '2020-10-10 13:20:56',
            ),
            69 => 
            array (
                'id' => 72,
                'name' => 'Primera División de Venezuela',
                'name_uk' => '["96509301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/venezuela/primera-division/',
                'importance' => '95.00',
                'country_id' => 231,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-15 19:12:39',
                'updated_at' => '2020-10-20 18:43:45',
            ),
            70 => 
            array (
                'id' => 73,
                'name' => 'Argentina Open',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/argentina-open/',
                'importance' => NULL,
                'country_id' => 11,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-02-15 19:16:08',
                'updated_at' => '2020-02-15 19:16:08',
            ),
            71 => 
            array (
                'id' => 74,
                'name' => 'Delray Beach Open - Masculino - Clasificación',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/usa/delray-beach-open-qualification-by-vitacost-com/',
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-02-15 19:24:40',
                'updated_at' => '2020-02-15 19:24:40',
            ),
            72 => 
            array (
                'id' => 75,
                'name' => 'Delray Beach Open - Masculino',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/usa/delray-beach-open-by-vitacost-com/',
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-02-20 17:45:25',
                'updated_at' => '2020-02-20 17:45:25',
            ),
            73 => 
            array (
                'id' => 76,
                'name' => 'Open 13 Marsella - Masculino',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/open-13/',
                'importance' => NULL,
                'country_id' => 73,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-02-20 17:47:13',
                'updated_at' => '2020-02-20 17:47:13',
            ),
            74 => 
            array (
                'id' => 77,
                'name' => 'Rio Open - Masculino',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/brazil/atp-rio-open-presented-by-claro/',
                'importance' => NULL,
                'country_id' => 31,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-02-20 17:48:42',
                'updated_at' => '2020-02-20 17:48:42',
            ),
            75 => 
            array (
                'id' => 78,
                'name' => 'Torneo de Doha - Femenino - Clasificación',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/qatar-total-open-qualification/',
                'importance' => NULL,
                'country_id' => 183,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-02-20 17:50:50',
                'updated_at' => '2020-02-20 17:50:50',
            ),
            76 => 
            array (
                'id' => 79,
                'name' => 'Torneo de Dubái',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/tennis/dubai-women\'s-singles-championship/',
                'importance' => NULL,
                'country_id' => 2,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-02-20 17:52:14',
                'updated_at' => '2020-02-20 17:52:14',
            ),
            77 => 
            array (
                'id' => 80,
                'name' => 'Copa Sudamericana',
                'name_uk' => '["689301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/americas/copa-sudamericana/',
                'importance' => '96.00',
                'country_id' => 243,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-25 09:34:07',
                'updated_at' => '2020-10-26 13:26:38',
            ),
            78 => 
            array (
                'id' => 81,
                'name' => 'CONCACAF Champions League',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/concacaf-champions-league/',
                'importance' => NULL,
                'country_id' => 242,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-26 16:25:04',
                'updated_at' => '2020-02-26 16:25:04',
            ),
            79 => 
            array (
                'id' => 82,
                'name' => 'Copa do Brasil',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/brazil/copa-do-brasil/',
                'importance' => NULL,
                'country_id' => 31,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-26 17:55:07',
                'updated_at' => '2020-02-26 17:55:07',
            ),
            80 => 
            array (
                'id' => 83,
                'name' => 'UEFA Europa League',
                'name_uk' => '["742010","virtual_europaLeagueMatches"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/uefa-europa-league/',
                'importance' => '1000.00',
                'country_id' => 245,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-02-26 17:56:17',
                'updated_at' => '2020-10-22 03:43:28',
            ),
            81 => 
            array (
                'id' => 84,
                'name' => 'MLB Pretemporada',
                'name_uk' => '["94904301"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/baseball/major-league-baseball-preseason/',
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 2,
                'match_structure_id' => 3,
                'created_at' => '2020-02-26 20:20:40',
                'updated_at' => '2020-07-19 16:01:06',
            ),
            82 => 
            array (
                'id' => 85,
                'name' => 'Copa Libertadores de América',
                'name_uk' => '["2124310","2124410","2124610","2124510","2124810","2124710","2124910","2125010"]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/americas/copa-libertadores-de-am%C3%A9rica/?showMostPopular=true',
                'importance' => '99.00',
                'country_id' => 243,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-03-02 20:00:42',
                'updated_at' => '2020-10-20 05:47:42',
            ),
            83 => 
            array (
                'id' => 86,
                'name' => 'Primera liga de Bielorrusa',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/belarus/vysshaya-liga/',
                'importance' => NULL,
                'country_id' => 36,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-04-24 05:58:40',
                'updated_at' => '2020-04-24 05:58:40',
            ),
            84 => 
            array (
                'id' => 87,
                'name' => 'KBO',
                'name_uk' => '[4395301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/baseball/korea-rep/korean-baseball-organization/',
                'importance' => NULL,
                'country_id' => 120,
                'category_id' => 2,
                'match_structure_id' => 3,
                'created_at' => '2020-05-16 08:02:02',
                'updated_at' => '2020-06-12 00:13:56',
            ),
            85 => 
            array (
                'id' => 88,
                'name' => 'K-League 1',
                'name_uk' => '[3284301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/korea-rep/korea-republic-k-league-1/',
                'importance' => NULL,
                'country_id' => 120,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-05-23 14:28:39',
                'updated_at' => '2020-06-13 00:05:34',
            ),
            86 => 
            array (
                'id' => 89,
                'name' => 'CPBL',
                'name_uk' => '[4908301]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/baseball/taiwan/taiwan-baseball-league/',
                'importance' => NULL,
                'country_id' => 223,
                'category_id' => 2,
                'match_structure_id' => 3,
                'created_at' => '2020-05-23 15:00:34',
                'updated_at' => '2020-06-12 21:43:11',
            ),
            87 => 
            array (
                'id' => 90,
                'name' => 'Copa de Vietnam',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/vietnam/vietnam-cup/',
                'importance' => NULL,
                'country_id' => 234,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-05-24 11:31:41',
                'updated_at' => '2020-05-24 11:31:41',
            ),
            88 => 
            array (
                'id' => 91,
                'name' => 'Primera División de República Checa',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/czech-republic/synot-liga/',
                'importance' => NULL,
                'country_id' => 54,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-05-26 15:11:58',
                'updated_at' => '2020-05-26 15:11:58',
            ),
            89 => 
            array (
                'id' => 92,
                'name' => 'Copa de Croacia',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/croatia/nogometni-kup/',
                'importance' => NULL,
                'country_id' => 96,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-05-30 06:35:15',
                'updated_at' => '2020-05-30 06:35:15',
            ),
            90 => 
            array (
                'id' => 93,
                'name' => 'Copa Alemana',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => 'http://odds.football-data.co.uk/football/germany/dfb-pokal/',
                'importance' => NULL,
                'country_id' => 55,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-06-07 17:41:44',
                'updated_at' => '2020-06-07 17:41:44',
            ),
            91 => 
            array (
                'id' => 94,
                'name' => 'Copa Italia',
                'name_uk' => '[35301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 108,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-06-11 21:48:34',
                'updated_at' => '2020-06-11 21:48:47',
            ),
            92 => 
            array (
                'id' => 95,
                'name' => 'Superliga de Grecia - Grupo de campeonato',
                'name_uk' => '[92225301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '16.00',
                'country_id' => 87,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-06-13 00:02:41',
                'updated_at' => '2020-06-20 22:20:16',
            ),
            93 => 
            array (
                'id' => 96,
                'name' => 'Superliga de Grecia - Grupo de descenso',
                'name_uk' => '[92227301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '15.00',
                'country_id' => 87,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-06-13 00:03:15',
                'updated_at' => '2020-06-20 22:20:12',
            ),
            94 => 
            array (
                'id' => 97,
                'name' => 'Superliga Danesa - Grupo de descenso',
                'name_uk' => '[58480301,58479301,"94807301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '9.00',
                'country_id' => 57,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-06-13 00:06:24',
                'updated_at' => '2020-07-12 14:20:11',
            ),
            95 => 
            array (
                'id' => 99,
                'name' => 'BBL',
                'name_uk' => '[6107301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '90.00',
                'country_id' => 55,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2020-06-13 00:16:42',
                'updated_at' => '2020-06-21 16:08:03',
            ),
            96 => 
            array (
                'id' => 100,
                'name' => 'Adria Tour - Masculino - Arcilla',
                'name_uk' => '[94277301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 186,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-13 03:24:21',
                'updated_at' => '2020-06-13 03:24:26',
            ),
            97 => 
            array (
                'id' => 101,
                'name' => 'Copa Élite Checa - Femenino - Arcilla',
                'name_uk' => '[2188410]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 54,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-13 03:41:31',
                'updated_at' => '2020-06-13 03:41:36',
            ),
            98 => 
            array (
                'id' => 102,
                'name' => 'NPB - Pretemporada',
                'name_uk' => '[2123310]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 112,
                'category_id' => 2,
                'match_structure_id' => 3,
                'created_at' => '2020-06-13 17:18:58',
                'updated_at' => '2020-06-13 17:19:10',
            ),
            99 => 
            array (
                'id' => 103,
                'name' => 'Liga ACB',
                'name_uk' => '["271301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '70.00',
                'country_id' => 66,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2020-06-16 19:07:07',
                'updated_at' => '2020-10-10 19:47:57',
            ),
        ));
        \DB::table('leagues')->insert(array (
            0 => 
            array (
                'id' => 104,
                'name' => 'NBLT',
                'name_uk' => '[93602301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 217,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2020-06-16 19:08:04',
                'updated_at' => '2020-06-16 19:08:19',
            ),
            1 => 
            array (
                'id' => 105,
                'name' => 'Austrian Pro Series',
                'name_uk' => '[94027301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 13,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-16 19:13:34',
                'updated_at' => '2020-06-16 19:13:43',
            ),
            2 => 
            array (
                'id' => 106,
                'name' => 'Eastern European Championship',
                'name_uk' => '[2189710]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 245,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-16 19:14:45',
                'updated_at' => '2020-06-16 19:14:54',
            ),
            3 => 
            array (
                'id' => 107,
                'name' => 'Campeonato Carioca - Taça Río',
                'name_uk' => '56321301',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 31,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-06-20 21:57:22',
                'updated_at' => '2020-07-12 09:55:29',
            ),
            4 => 
            array (
                'id' => 108,
                'name' => 'CBA',
                'name_uk' => '[10233301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 47,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2020-06-20 22:26:10',
                'updated_at' => '2020-06-20 22:26:19',
            ),
            5 => 
            array (
                'id' => 109,
                'name' => 'Superliga de baloncesto de Grecia',
                'name_uk' => '[1804301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 87,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2020-06-20 22:29:09',
                'updated_at' => '2020-06-20 22:29:20',
            ),
            6 => 
            array (
                'id' => 110,
                'name' => 'NPB',
                'name_uk' => '[2098301, 2099301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 112,
                'category_id' => 2,
                'match_structure_id' => 3,
                'created_at' => '2020-06-20 22:32:37',
                'updated_at' => '2020-06-20 22:32:46',
            ),
            7 => 
            array (
                'id' => 111,
                'name' => 'Ultimate Fighting Championship',
                'name_uk' => '[11810]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 241,
                'category_id' => 10,
                'match_structure_id' => 0,
                'created_at' => '2020-06-20 22:35:52',
                'updated_at' => '2020-06-20 22:36:31',
            ),
            8 => 
            array (
                'id' => 112,
                'name' => 'Battle od the Brits',
                'name_uk' => '[2194510]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 75,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-22 18:31:13',
                'updated_at' => '2020-06-22 18:31:20',
            ),
            9 => 
            array (
                'id' => 113,
                'name' => 'Exhibition MatchPlay 120',
                'name_uk' => '[94135301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-22 18:48:44',
                'updated_at' => '2020-06-22 18:50:55',
            ),
            10 => 
            array (
                'id' => 114,
                'name' => 'Inivitación de USA - Femenino',
                'name_uk' => '[2194810]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-22 19:48:34',
                'updated_at' => '2020-06-22 19:48:42',
            ),
            11 => 
            array (
                'id' => 115,
                'name' => 'US Pro Series Tennis - Masculino',
                'name_uk' => '[94224301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-23 05:11:20',
                'updated_at' => '2020-06-23 05:11:44',
            ),
            12 => 
            array (
                'id' => 116,
                'name' => 'US Pro Series Tennis - Femenino',
                'name_uk' => '[93867301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-23 05:12:07',
                'updated_at' => '2020-06-23 05:12:11',
            ),
            13 => 
            array (
                'id' => 117,
                'name' => 'GST MatchPlay 120 - Femenino',
                'name_uk' => '[94137301]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-23 05:13:39',
                'updated_at' => '2020-06-23 05:13:46',
            ),
            14 => 
            array (
                'id' => 118,
                'name' => 'FPT Portugal Series - Masculino',
                'name_uk' => '[2193910]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 180,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-23 05:15:41',
                'updated_at' => '2020-06-23 05:15:53',
            ),
            15 => 
            array (
                'id' => 119,
                'name' => 'FPT Portugal Series - Femenino',
                'name_uk' => '[2194010]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 180,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-23 05:16:13',
                'updated_at' => '2020-06-23 05:16:17',
            ),
            16 => 
            array (
                'id' => 120,
                'name' => 'Italian Championship - Masculino',
                'name_uk' => '[2194310]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 108,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-06-23 05:17:59',
                'updated_at' => '2020-06-23 05:18:04',
            ),
            17 => 
            array (
                'id' => 121,
                'name' => 'MLS',
                'name_uk' => '["94343301","94345301","94347301","94349301","94351301","94353301","94355301","18301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '700.00',
                'country_id' => 226,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-07-12 14:04:35',
                'updated_at' => '2020-10-22 14:02:39',
            ),
            18 => 
            array (
                'id' => 122,
                'name' => 'Copa por México',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 153,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-07-12 14:17:41',
                'updated_at' => '2020-07-12 14:17:41',
            ),
            19 => 
            array (
                'id' => 123,
                'name' => 'Campeonato Cearense',
                'name_uk' => '[]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 31,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-07-12 14:23:18',
                'updated_at' => '2020-07-12 14:23:18',
            ),
            20 => 
            array (
                'id' => 124,
                'name' => 'Campeonato Paulista',
                'name_uk' => '["56342301","56344301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 31,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-07-21 18:46:03',
                'updated_at' => '2020-08-02 11:46:24',
            ),
            21 => 
            array (
                'id' => 125,
                'name' => 'J-League',
                'name_uk' => '["82301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 112,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-07-21 18:49:50',
                'updated_at' => '2020-07-21 18:49:54',
            ),
            22 => 
            array (
                'id' => 126,
                'name' => 'Primera división de Rusia',
                'name_uk' => '["53301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 187,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-07-21 18:50:36',
                'updated_at' => '2020-07-21 18:50:38',
            ),
            23 => 
            array (
                'id' => 127,
                'name' => 'Eastern European Championship - Masculino',
                'name_uk' => '["94323301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 245,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-07-21 18:52:14',
                'updated_at' => '2020-07-21 18:53:21',
            ),
            24 => 
            array (
                'id' => 128,
                'name' => 'Eastern European Championship - Femenino',
                'name_uk' => '["94324301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 245,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-07-21 18:53:39',
                'updated_at' => '2020-07-21 18:53:46',
            ),
            25 => 
            array (
                'id' => 129,
                'name' => 'Superliga China',
                'name_uk' => '["652301","96609301","96611301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 47,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-07-26 20:40:33',
                'updated_at' => '2020-10-20 18:37:27',
            ),
            26 => 
            array (
                'id' => 130,
                'name' => 'WTA Torneo de Praga',
                'name_uk' => '["88728301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 54,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-08-09 11:13:03',
                'updated_at' => '2020-08-09 11:13:18',
            ),
            27 => 
            array (
                'id' => 131,
                'name' => 'Torneo de Lexington',
                'name_uk' => '["94831301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-08-09 15:07:32',
                'updated_at' => '2020-08-09 15:07:39',
            ),
            28 => 
            array (
                'id' => 132,
                'name' => 'WNBA',
                'name_uk' => '["591301","11419301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2020-08-09 15:47:20',
                'updated_at' => '2020-10-04 09:32:02',
            ),
            29 => 
            array (
                'id' => 133,
            'name' => 'Liga de Campeones de Europa (Clasificatorios)',
                'name_uk' => '["810610"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 245,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-08-17 16:28:09',
                'updated_at' => '2020-08-17 16:28:21',
            ),
            30 => 
            array (
                'id' => 134,
                'name' => 'US Open - Masculino',
                'name_uk' => '["86356301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-02 15:23:23',
                'updated_at' => '2020-09-07 17:40:16',
            ),
            31 => 
            array (
                'id' => 135,
                'name' => 'US Open - Femenino',
                'name_uk' => '["86358301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 226,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-07 17:41:08',
                'updated_at' => '2020-09-07 17:41:12',
            ),
            32 => 
            array (
                'id' => 136,
                'name' => 'Abierto de Estambul - Femenino',
                'name_uk' => '["90609301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 220,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-07 17:49:55',
                'updated_at' => '2020-09-07 17:50:00',
            ),
            33 => 
            array (
                'id' => 137,
                'name' => 'Masters de Roma - Masculino - Clasificación',
                'name_uk' => '["89252301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 108,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-12 17:35:25',
                'updated_at' => '2020-09-12 17:35:32',
            ),
            34 => 
            array (
                'id' => 138,
                'name' => 'Masters de Roma - Femenino - Clasificación',
                'name_uk' => '["88736301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 108,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-12 17:36:15',
                'updated_at' => '2020-09-12 17:36:28',
            ),
            35 => 
            array (
                'id' => 139,
                'name' => 'Masters de Roma - Masculino',
                'name_uk' => '["89253301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 108,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-14 18:15:19',
                'updated_at' => '2020-09-14 18:15:46',
            ),
            36 => 
            array (
                'id' => 140,
                'name' => 'Masters de Roma - Femenino',
                'name_uk' => '["88737301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 108,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-14 18:15:32',
                'updated_at' => '2020-09-14 18:16:09',
            ),
            37 => 
            array (
                'id' => 141,
                'name' => 'Torneo de Hamburgo - Masculino',
                'name_uk' => '["89291301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 55,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-20 18:55:17',
                'updated_at' => '2020-09-20 18:55:22',
            ),
            38 => 
            array (
                'id' => 142,
                'name' => 'Torneo de Estrasburgo - Femenino',
                'name_uk' => '["88743301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 73,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-20 18:56:38',
                'updated_at' => '2020-09-20 18:56:46',
            ),
            39 => 
            array (
                'id' => 143,
                'name' => 'Abierto de Francia Calificación - Masculino',
                'name_uk' => '["89261301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 73,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-21 10:40:09',
                'updated_at' => '2020-09-21 10:40:26',
            ),
            40 => 
            array (
                'id' => 144,
                'name' => 'Abierto de Francia Calificación - Femenino',
                'name_uk' => '["88745301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 73,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-21 10:40:55',
                'updated_at' => '2020-09-21 10:40:59',
            ),
            41 => 
            array (
                'id' => 145,
                'name' => 'Abierto de Francia - Masculino',
                'name_uk' => '["82834301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '100.00',
                'country_id' => 73,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-27 09:36:27',
                'updated_at' => '2020-10-08 18:10:18',
            ),
            42 => 
            array (
                'id' => 146,
                'name' => 'Abierto de Francia - Femenino',
                'name_uk' => '["82835301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '100.00',
                'country_id' => 73,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-09-27 09:37:16',
                'updated_at' => '2020-10-08 18:10:15',
            ),
            43 => 
            array (
                'id' => 147,
                'name' => 'Eliminatorias CONMEBOL para la Copa Mundial de Fútbol',
                'name_uk' => '["1806310"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '1000.00',
                'country_id' => 243,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-10-08 15:42:19',
                'updated_at' => '2020-10-08 15:42:49',
            ),
            44 => 
            array (
                'id' => 148,
                'name' => 'Amistosos internacionales',
                'name_uk' => '["66301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 241,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-10-08 16:07:30',
                'updated_at' => '2020-10-08 16:07:34',
            ),
            45 => 
            array (
                'id' => 149,
                'name' => 'Challenger de Barcelona - Masculino',
                'name_uk' => '["95781301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 66,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-10-08 18:09:18',
                'updated_at' => '2020-10-08 18:09:22',
            ),
            46 => 
            array (
                'id' => 150,
                'name' => 'Challenger de Parma - Masculino',
                'name_uk' => '["94765301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 108,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-10-08 18:10:34',
                'updated_at' => '2020-10-08 18:10:39',
            ),
            47 => 
            array (
                'id' => 151,
                'name' => 'Abierto de San Petersburgo - Clasificación - Masculino',
                'name_uk' => '["89380301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 187,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-10-10 08:23:19',
                'updated_at' => '2020-10-10 08:23:41',
            ),
            48 => 
            array (
                'id' => 152,
                'name' => 'Abierto de San Petersburgo - Masculino',
                'name_uk' => '["89381301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 187,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-10-10 08:24:18',
                'updated_at' => '2020-10-10 08:24:21',
            ),
            49 => 
            array (
                'id' => 153,
                'name' => 'Challenger de Lisboa - Clasificatorios - Masculino',
                'name_uk' => '["95791301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 180,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-10-10 08:27:02',
                'updated_at' => '2020-10-10 08:27:11',
            ),
            50 => 
            array (
                'id' => 154,
                'name' => 'Liga de las Naciones de la UEFA - Liga A',
                'name_uk' => '["uefaLeagueGroupA","virtual_uefaLeagueGroupA"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '1000.00',
                'country_id' => 245,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-10-10 14:15:52',
                'updated_at' => '2020-10-28 06:01:00',
            ),
            51 => 
            array (
                'id' => 155,
                'name' => 'Liga de las Naciones de la UEFA - Liga B',
                'name_uk' => '["uefaLeagueGroupB","virtual_uefaLeagueGroupB"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '999.00',
                'country_id' => 245,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-10-10 14:19:19',
                'updated_at' => '2020-10-28 06:01:13',
            ),
            52 => 
            array (
                'id' => 156,
                'name' => 'Liga de las Naciones de la UEFA - Liga C',
                'name_uk' => '["uefaLeagueGroupC"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '998.00',
                'country_id' => 245,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-10-10 14:20:00',
                'updated_at' => '2020-10-10 14:20:19',
            ),
            53 => 
            array (
                'id' => 157,
                'name' => 'European Open - Masculino',
                'name_uk' => '["89422301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '100.00',
                'country_id' => 21,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-10-17 21:45:05',
                'updated_at' => '2020-10-20 19:06:53',
            ),
            54 => 
            array (
                'id' => 158,
                'name' => 'Copa Colombia',
                'name_uk' => '["5269301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 48,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-10-20 18:38:05',
                'updated_at' => '2020-10-20 18:38:11',
            ),
            55 => 
            array (
                'id' => 159,
                'name' => 'Taca do Portugal',
                'name_uk' => '["207301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 180,
                'category_id' => 1,
                'match_structure_id' => 4,
                'created_at' => '2020-10-20 18:42:37',
                'updated_at' => '2020-10-20 18:42:48',
            ),
            56 => 
            array (
                'id' => 160,
                'name' => 'Bett1Hulks Championship - Masculino',
                'name_uk' => '["96037301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '95.00',
                'country_id' => 55,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-10-20 19:00:17',
                'updated_at' => '2020-10-20 19:07:49',
            ),
            57 => 
            array (
                'id' => 161,
                'name' => 'Ostrava Open - Femenino',
                'name_uk' => '["96049301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '90.00',
                'country_id' => 54,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-10-20 19:01:27',
                'updated_at' => '2020-10-20 19:07:22',
            ),
            58 => 
            array (
                'id' => 162,
                'name' => 'Challenger Estambul - Masculino',
                'name_uk' => '["96093301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 220,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-10-20 19:03:07',
                'updated_at' => '2020-10-20 19:03:50',
            ),
            59 => 
            array (
                'id' => 163,
                'name' => 'Challenger Ismaning - Masculino',
                'name_uk' => '["96099301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 55,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-10-20 19:04:24',
                'updated_at' => '2020-10-20 19:06:42',
            ),
            60 => 
            array (
                'id' => 164,
                'name' => 'W25+H Cherburgo-en-Cotentin 26A - Femenino',
                'name_uk' => '["96711301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 73,
                'category_id' => 4,
                'match_structure_id' => 1,
                'created_at' => '2020-10-20 19:05:57',
                'updated_at' => '2020-10-20 19:06:04',
            ),
            61 => 
            array (
                'id' => 165,
                'name' => 'Eurocopa',
                'name_uk' => '["virtual_basketballEurocup","virtual_basketballEurocup-96405301-96409301-96411301-74674301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 245,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2020-10-20 19:09:47',
                'updated_at' => '2020-10-28 05:44:12',
            ),
            62 => 
            array (
                'id' => 166,
                'name' => 'Champions League',
                'name_uk' => '["54378301","96401301","96403301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 245,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2020-10-20 19:11:15',
                'updated_at' => '2020-10-29 09:59:31',
            ),
            63 => 
            array (
                'id' => 167,
                'name' => 'ABA League',
                'name_uk' => '["2451301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => NULL,
                'country_id' => 245,
                'category_id' => 3,
                'match_structure_id' => 5,
                'created_at' => '2020-10-20 19:12:51',
                'updated_at' => '2020-10-20 19:13:43',
            ),
            64 => 
            array (
                'id' => 168,
                'name' => 'Astana Open - Masculino',
                'name_uk' => '["96043301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '90.00',
                'country_id' => 123,
                'category_id' => 4,
                'match_structure_id' => 0,
                'created_at' => '2020-10-25 17:53:17',
                'updated_at' => '2020-10-25 17:58:50',
            ),
            65 => 
            array (
                'id' => 169,
                'name' => 'Astana Open - Clasificatorios - Masculino',
                'name_uk' => '["96041301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '50.00',
                'country_id' => 123,
                'category_id' => 4,
                'match_structure_id' => 0,
                'created_at' => '2020-10-25 17:54:24',
                'updated_at' => '2020-10-25 17:58:41',
            ),
            66 => 
            array (
                'id' => 170,
                'name' => 'Torneo de Viena - Masculino',
                'name_uk' => '["89436301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '90.00',
                'country_id' => 13,
                'category_id' => 4,
                'match_structure_id' => 0,
                'created_at' => '2020-10-25 17:55:17',
                'updated_at' => '2020-10-25 17:58:39',
            ),
            67 => 
            array (
                'id' => 171,
                'name' => 'Challenger Hamburgo - Masculino',
                'name_uk' => '["96105301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '1.00',
                'country_id' => 55,
                'category_id' => 4,
                'match_structure_id' => 0,
                'created_at' => '2020-10-25 17:56:27',
                'updated_at' => '2020-10-25 17:58:51',
            ),
            68 => 
            array (
                'id' => 172,
                'name' => 'Challenger Marbella - Masculino',
                'name_uk' => '["90824301"]',
                'description' => NULL,
                'url' => NULL,
                'importance' => '1.00',
                'country_id' => 66,
                'category_id' => 4,
                'match_structure_id' => 0,
                'created_at' => '2020-10-25 17:57:19',
                'updated_at' => '2020-10-25 17:58:51',
            ),
        ));
        
        
    }
}